export const FETCH_NOTES = `NOTES/FETCH_NOTES`;
export const SELECT_NOTE = `NOTES/SELECT_NOTE`;
export const CREATE_NOTE = `NOTES/CREATE_NOTE`;
export const EDIT_NOTE = `NOTES/EDIT_NOTE`;
export const MOVE_NOTE_TO_TRASH = `NOTES/MOVE_NOTE_TO_TRASH`;
export const DELETE_NOTE = `NOTES/DELETE_NOTE`;
export const SET_SEARCH_VAL = `NOTES/SET_SEARCH_VAL`;
